on: [push, pull_request]
name: validate
jobs:
  kubeval:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: manifest
      uses: instrumenta/kubeval-action@master
      with:
       files: jenkins.yaml
  slack:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: igoz_notification_channel
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: "icon_emoji": ":ghost:"
        SLACK_MESSAGE: 'Kubeval test'
        SLACK_TITLE: 'job is done'
        SLACK_USERNAME: Kubeval
        SLACK_WEBHOOK: ${{ secrets.WEBHOOK }
